### ISSUE TITLE
CLI is currently broken

### ISSUE THREAD

**Issue by strazzere** [strazzere/duml-packet#1]
Hadn't noticed until now, would be a good first issue for someone to fix as well as adding a test to ensure it doesn't break in the future;

```
> duml-packet@2.0.0 cli
> ts-node dist/cli.js

file:///home/diff/repo/rednaga/dumlpacket/node_modules/yargs/lib/platform-shims/esm.mjs:38
    throw new YError(REQUIRE_DIRECTORY_ERROR)
          ^
YError: loading a directory of commands is not supported yet for ESM
    at Object.getCallerFile (file:///home/diff/repo/rednaga/dumlpacket/node_modules/yargs/lib/platform-shims/esm.mjs:38:11)
    at YargsInstance.commandDir (file:///home/diff/repo/rednaga/dumlpacket/node_modules/yargs/build/lib/yargs-factory.js:296:145)
    at file:///home/diff/repo/rednaga/dumlpacket/src/cli.ts:6:4
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

**Comment by strazzere** [comment]
Closed via fc46f6d
